TugasKelompok/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("testing/", include("home.urls")),
    path("", include("login_page.urls")),
    path("", include("home_page.urls")),
    path("", include("shopping_cart_page.urls")),
    path("", include("product_list_page.urls")),
    path("", include("wishlist_page.urls")),
    path("", include("checkout_page.urls")),
    path("", include("cuztomize_masker_page.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("testing/", views.testing, name="testing"),
]

home_page/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index),
    path('ajax/get_image', get_image),
    path('ajax/subscribe', subscribe),
    path('unsubscribe/<id>', unsubscribe),
    path('api/mobile/get-data/<max_data>', mobile_get_data),
    path('api/mobile/subscribe', mobile_subscribe),
]

home/models.py
from django.db import models

# Create your models here.

home_page/models.py
from django.db import models

# Create your models here.


class WishlistItem(models.Model):
    name = models.CharField(max_length=30)
    count = models.IntegerField()

class SubscribedEmail(models.Model):
    email = models.EmailField(unique=True)

home_page/forms.py
from django import forms
from .models import SubscribedEmail


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = SubscribedEmail
        fields = "__all__"

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, "home/index.html")


def testing(request):
    return HttpResponse("Hello world")

home_page/views.py
import json
from django.http.response import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, render
from home_page.forms import SubscribeForm
from home_page.models import SubscribedEmail
from django.db.models.signals import post_save
from django.dispatch import receiver
from product_list_page.models import ProdukMasker
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import threading


# Create your views here.
def index(request) :

    return render(request, 'home_page/home.html')

adder = [1]
def get_image(request):
    if request.is_ajax() and request.method == 'GET':
        request_content = request.GET
        cur_counter = int(request_content["current_counter"]) + adder[0]
        masker = get_object_or_404(ProdukMasker, id=cur_counter)
        data = {
            "src" : masker.imageURL,
            "title":masker.nama,
            "price":"$" + str(masker.harga)
        }
        return JsonResponse(data, status=200)
    else:
        return HttpResponseNotFound()    


def mobile_get_data(request, max_data):
    data = ProdukMasker.objects.values()[:int(max_data)]

    # ambil url gambar cloudinary
    for e in data:
        if e["image"]:
            e["image"] = e["image"].build_url()
    
    return JsonResponse(list(data), safe=False)

@csrf_exempt
def mobile_subscribe(request):
    print("aaa")
    if request.method == "POST":
        email_dict = json.loads(request.body)
        form = SubscribeForm(email_dict)
        if form.is_valid():
            form.save()
            return JsonResponse({"message": "Thank You"}, status=200)
        else:
            return JsonResponse({"message": "duplicate"}, status=200)
    else:
        return HttpResponseNotFound()



def subscribe(request):
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({"message": "Thank You"}, status=200)
        else:
            return JsonResponse({"message": "duplicate"}, status=200)
    else:
        return HttpResponseNotFound()



@receiver(post_save, sender=ProdukMasker)
def produk_masker_handler(sender, **produk) :
    def mysender():
        nama_produk = produk["instance"].nama
        deskripsi = produk["instance"].deskripsi
        stok = produk["instance"].stok
        price = produk["instance"].harga
        url_image = produk["instance"].imageURL

        for pk, dest in [(semail.pk, semail.email) for semail in SubscribedEmail.objects.all()]:
            email = EmailMultiAlternatives(
                subject="New Mask is Out !!!",
                body=f"""
                {nama_produk}
                deskripsi: {deskripsi}
                stok: {stok}
                price: {price}
                """,
                from_email= settings.EMAIL_HOST_USER,
                to=[dest],
            )
            html_style = """
            <style>
                h1, h4 {
                    color: black;
                }
            </style>\n
            """

            html_content = f"""
            <h1> {nama_produk} </h1>
            <h4> deskripsi: {deskripsi} </h4>
            <h4> stok:  {stok} <h4>
            <h4> harga: ${price} <h4>
            <img src="{url_image}">
            <a href="https://pbp-c07.herokuapp.com/unsubscribe/{pk}">Unsubscribe</a>
            """

            html_content = html_style + html_content
            email.attach_alternative(html_content, 'text/html')
            email.send()

    t = threading.Thread(target=mysender, daemon=True)
    t.start()

def unsubscribe(request, id):
    try:
        subscribe_email = get_object_or_404(SubscribedEmail ,id=id)
        subscribe_email.delete()
        return HttpResponse('You have unsubscribed our newsletter', status=200)
    except:
        return HttpResponse('Email not found', status=404)

home_page/templates/home_page/home.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Home Page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">  
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/4.1.0/mustache.min.js" integrity="sha512-HYiNpwSxYuji84SQbCU5m9kHEsRqwWypXgJMBtbRSumlx1iBB6QaxgEBZHSHEGM+fKyCX/3Kb5V5jeVXm0OglQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        {% include "home_page/home_navbar.html" %}
        <link rel="stylesheet" type="text/css" href='{% static "css/fitur-masker.css" %}'>
    </head>
    <body>
        <div class = "container" id="fitur-container">
            
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">Terpercaya</h5>
                    <p class="card-text">Masker kami memiliki tingkat filtrasi hingga 70%</p>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">Higienis</h5>
                    <p class="card-text">Kesterilan produk masker dijaga hingga ke tangan pembeli</p>
                </div>
            </div>
            <div class="card">
                <div class="card-body" >
                    <h1 class="card-title">Fashionable</h5>
                    <p class="card-text">Tidak hanya faktor kesehatan, kami selalu berusaha untuk menjaga faktor estetika produk masker kami</p>
                </div>
            </div>
        </div>
        <div class="container" id="outer-container" style="position: relative; margin-top: 2rem;">
            <div class="container" style="position: relative;">
                <a href="/product_list_page/">
                    <button type="button" class="btn btn-success" style="position: absolute; right: 0;">Lihat Masker Lainnya</button>
                </a>
            </div>
            <div class="container" id="product-summary-container">
                <div class="container" id="no-product-message-container">
                    <p style="align-self:center; margin: auto; padding: 5px;"><strong>Belum Ada Masker yang Ditambahkan</strong><p>
                </div>
            </div>
            <a class="prev">❮</a>
            <a class="next" >❯</a>
        </div>
        <script type="text/javascript" src="{% static 'js/product-summary.js' %}"></script>
    </body>
    {% include "home_page/home_footer.html" %}   
</html>

home_page/templates/home_page/home_footer.html
{% load static %}

<link rel="stylesheet" type="text/css" href='{% static "css/home_footer.css" %}'>
<footer class="fluid-container">
    <div class="fluid-container">
        <div class="container" id="subscription-container">
            <form class="row g-2" id="footer-subscribe-form" action="" method="POST">
                {% csrf_token %}
                <label for="id_email" class="form-label" style="color:rgb(235, 233, 233); text-align: center;">Subscribe to our Newsletter</label>
                    
                <div class="input-group mb-3">
                    <input type="email" class="form-control" name="email" id="id_email" placeholder="email@example.com" aria-label="Recipient's email" aria-describedby="button-addon2">
                    <button class="btn btn-outline-warning" type="submit" id="button-addon2" value="Submit">Subscribe</button>
                </div>
            </form>
        </div>

        <div class="container" id="contact-us-container">
            <h style="color:rgb(235, 233, 233); text-align: center;">Contact Us</h>
            <div class="container">
                    <a href="https://twitter.com/twitter">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="gray" class="bi bi-twitter" viewBox="0 0 16 16">
                            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                        </svg>
                    </a>
                    <a href="https://web.facebook.com/Facebook-249443538526027/?brand_redir=108824017345866">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="gray" class="bi bi-facebook" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                        </svg>
                    </a>

                    <a href="https://www.instagram.com/instagram/">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="gray" class="bi bi-instagram" viewBox="0 0 16 16">
                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                        </svg>
                    </a>
                
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/subscribe.js' %}"></script>
</footer>

home_page/templates/home_page/home_navbar.html
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href='{% static "css/navbar.css" %}'>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="home_navbar">
    <div class="container" style="width: 100%; align-items: center; display: flex;">
      <div class="fluid-container" style="margin: 10px;">
        <button class="navbar-toggler" type="button" style="align-self: center;" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    
      <a href="/cart/" style="margin-right: 25px; align-self: center;" id="cart-for-mobile" style="background-color: red;">
        <img  id="cart-icon" src="{% static 'images/cart.png' %}">
      </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %} 
            <li class="nav-item" id="username-for-mobile">
              <span class="navbar-text">Welcome, {{ user.username }}</span>
            </li>
          {% endif %}
          <li class="nav-item" id="home_btn_navbar">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/product_list_page/">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/wishlist/">Wishlist</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" href="/custom-mask/">Customize Mask</a>
            </li>
          {% endif %}
        </ul>
        <form class="d-flex" style="display: flex;">
          <a href="/cart/" style="margin-right: 25px; align-self: center;" id="cart-for-dekstop">
            <img  id="cart-icon" src="{% static 'images/cart.png' %}">
          </a>
          {% if not user.is_authenticated %}
            <a type="button" class="btn btn-primary" id="navbar-login">Login</a>
          {% else %}
            <span class="navbar-text" style="padding-right: 10px;">Welcome, {{ user.username }}</span>
            <a type="button" class="btn btn-primary" href="../logout">Logout</a>
          {% endif %}
        </form>
      </div>
    </div>
</nav>
<script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>